---
title: "R Notebook"
output: html_notebook
---

```{r}
library(magrittr) # needs to be run every time you start R and want to use %>%
library(dplyr)
```

```{r}
#' A single play of the Martingale strategy
#'
#' Takes a state list, spins the roulette wheel, returns the state list with updated values (for example, budget, plays, etc)
#' @param state A list with the following entries: 
#'   B              number, the budget
#'   W              number, the budget threshold for successfully stoping
#'   L              number, the maximum number of plays 
#'   M              number, the casino wager limit
#'   plays          integer, the number of plays executed
#'   previous_wager number, the wager in the previous play (0 at first play)
#'   previous_win   TRUE/FALSE, indicator if the previous play was a win (TRUE at first play)
#' @return The updated state list
```



```{r}
one_play <- function(state){
  
    # Wager
    proposed_wager <- ifelse(state$previous_win, 1, 2*state$previous_wager)
    wager <- min(proposed_wager, state$M, state$B)
    
    # Spin of the wheel
    red <- rbinom(1,1,18/38)
    
    # Update state
    state$plays <- state$plays + 1
    state$previous_wager <- wager
    if(red){
      # WIN
      state$B <- state$B + wager
      state$previous_win <- TRUE
    }else{
      # LOSE
      state$B <- state$B - wager
      state$previous_win <- FALSE
    }
  state
}
```


```{r}
#' Stopping rule
#'
#' Takes the state list and determines if the gambler has to stop
#' @param state A list.  See one_play
#' @return TRUE/FALSE


stop_play <- function(state){
  if(state$B <= 0) return(TRUE)
  if(state$plays >= state$L) return(TRUE)
  if(state$B >= state$W) return(TRUE)
  FALSE
}
```


```{r}
#' Play roulette to either bankruptcy, success, or play limits
#'
#' @param B number, the starting budget
#' @param W number, the budget threshold for successfully stoping
#' @param L number, the maximum number of plays 
#' @param M number, the casino wager limit
#' @return A vector of budget values calculated after each play.
one_series <- function(
    B = 200
  , W = 300
  , L = 1000
  , M = 100
){

  # initial state
  state <- list(
    B = B
  , W = W
  , L = L
  , M = M
  , plays = 0
  , previous_wager = 0
  , previous_win = TRUE
  )
  
  # vector to store budget over series of plays
  budget <- rep(NA, L)
  
  # For loop of plays
  for(i in 1:L){
    new_state <- state %>% one_play
    budget[i] <- new_state$B
    if(new_state %>% stop_play){
      return(budget[1:i])
    }
    state <- new_state
  }
  budget    
}

# helper function
get_last <- function(x) x[length(x)] 

```


```{r}
# Simulation
walk_out_money <- rep(NA, 10000)
for(j in seq_along(walk_out_money)){
  walk_out_money[j] <- one_series(B = 200, W = 300, L = 1000, M = 100) %>% get_last
}

# Walk out money distribution
hist(walk_out_money, breaks = 10)

# Estimated probability of walking out with extra cash
mean(walk_out_money > 200)

# Estimated earnings
mean(walk_out_money - 200)
```
```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
library(tidyverse)
library(ggplot2)
```



```{r}
# Q2
earning <- one_series(B = 200, W = 300, L = 1000, M = 100) - 200
plot(earning, main = "Gamblers earnings / losses over time", xlab = "play number", 
     ylab = "earnings")
```

```{r}
# change the budget
walk_out_money <- rep(NA, 100)
b <- matrix(nrow = 100, ncol = 16)

for(i in seq(1, 16)){
  for(j in seq_along(walk_out_money)){
    b[j, i] <- one_series(B= 20 * i, W = 300, L = 1000, M = 200) %>% get_last
  }
}

# Estimated earnings
mean_earnings <- colMeans(b) - 200

# plot earnings
plot(mean_earnings)

```

```{r}
# change the winning

walk_out_money <- rep(NA, 100)
w <- matrix(nrow = 100, ncol = 16)

for(i in seq(1, 16)){
  for(j in seq_along(walk_out_money)){
    w[j, i] <- one_series(B= 200, W = 40 * i, L = 1000, M = 200) %>% get_last
  }
}

# Estimated earnings
mean_earnings <- colMeans(w) - 200

# plot earnings
plot(mean_earnings)
```


```{r}
# change time threshold
walk_out_money <- rep(NA, 100)
l <- matrix(nrow = 100, ncol = 16)

for(i in seq(1, 16)){
  for(j in seq_along(walk_out_money)){
    l[j, i] <- one_series(B= 200, W = 300, L = 20 * i, M = 200) %>% get_last
  }
}

# Estimated earnings
mean_earnings <- colMeans(l) - 200

# plot earnings
plot(mean_earnings)
```

```{r}
# change max
walk_out_money <- rep(NA, 100)
m <- matrix(nrow = 100, ncol = 16)

for(i in seq(1, 16)){
  for(j in seq_along(walk_out_money)){
    m[j, i] <- one_series(B= 200, W = 300, L = 1000, M = 10 * i) %>% get_last
  }
}

# Estimated earnings
mean_earnings <- colMeans(m) - 200

# plot earnings
plot(mean_earnings)
```









```{r}
# Q4: average number of plays
# Simulation
num_play <- function(x) length(x) 

walk_out_play <- rep(NA, 100)
for(j in seq_along(walk_out_play)){
  walk_out_play[j] <- one_series(B = 200, W = 300, L = 1000, M = 100) %>% num_play
}

# Walk out money distribution
hist(walk_out_play, breaks = 10)


# Estimated earnings
mean(walk_out_play)

```